version: "3.8"

services:
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    expose:
      - 27017/tcp
    volumes:
      - db:/data/db
  app:
    depends_on:
      mongodb:
        condition: service_started
    build: .
    restart: "unless-stopped"
    env_file:
      - .env
    environment:
      - DIVAR_URLS=$DIVAR_URLS
      - NODE_LOCAL_PORT=$NODE_LOCAL_PORT
      - NODE_DOCKER_PORT=$NODE_DOCKER_PORT
      - TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN
      - TELEGRAM_CHAT_IDS=$TELEGRAM_CHAT_IDS
      - SLEEP_TIME=10000
    stdin_open: true
    tty: true


volumes:
  db:

